version: 0.2
   
phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - rm -f /etc/apt/sources.list.d/sbt.list
      - apt-get update --assume-yes --no-install-recommends
      - gem install bundler -v 2.4.22
      - bundle install
  build:
    commands:
      - echo "******** Jekyll Build command ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://hiu.state.gov
      - echo "******** Deleting AWS CloudFront Cache ********"
      - aws cloudfront create-invalidation --distribution-id E10JKYM6CSTS12 --paths '/*'
